[package]
name = "nphysics-playground"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2018"

[dependencies]
nalgebra = "0.17"
# Choose the one you need, or both.
ncollide2d = "0.18"
# Choose the one you need, or both.
nphysics2d = "0.10.2"

